# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5

install:
  - pip install -r requirements_dev.txt
  - pip install pytest pytest-cov coveralls

# command to run tests, e.g. python setup.py test
script:
  - python -m pytest tests/
  # - pytest tests --cov
  # - coveralls

# deploy new versions to PyPI
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: meowmix
  password:
    secure: foobar
  on:
    tags: true
    repo: spacetelescope/awesimsoss
    python: 3.5