# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5

install:
  - pip install -r requirements_dev.txt
  - pip install -e .
  - pip install pytest pytest-cov coveralls

# command to run tests, e.g. python setup.py test
script:
  # - python -m pytest tests/
  - pytest --cov=awesimsoss/

after_success:
  - coveralls

# deploy new versions to PyPI
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: "__token__"
  password:
    secure: "pypi-AgEIcHlwaS5vcmcCJDk1YWM2MWJiLWJkY2YtNDZmMC05YWNlLTAzNDYyZTgxZGVlYwACO3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJhd2VzaW1zb3NzIl19LCAidmVyc2lvbiI6IDF9AAAGIMtrbKrXoSda3BcSs59WkNb8gdiTvfeGosbRn1GA7FQD"
    tags: true
    repo: spacetelescope/awesimsoss
    python: 3.5
  on:
    tags: true